- name: Copying over AMQ Subscription
  template:
    src: templates/amq-sub.yaml.j2
    dest:  "{{ config_location }}/amq-sub.yaml"
    owner: "{{ default_owner }}"
    group: "{{ default_group }}"
    mode: 0666

- name: Create Subscription to AMQ
  command: "oc create -f {{ config_location }}/amq-sub.yaml"
  register: rbac_result

- name: Waiting for  AMQ Subscription to complete
  shell: |
    set -o pipefail && oc get csv | grep {{ amqstartingCSV }}
  register: install_status
  until: "'Succeeded' in install_status.stdout"
  retries: 60
  delay: 15
  args:
    executable: /bin/bash

- name: Copying over kafka config
  template:
    src: templates/amq-kafka-instance.yaml.j2
    dest:  "{{ config_location }}/amq-kafka-instance.yaml"
    owner: "{{ default_owner }}"
    group: "{{ default_group }}"
    mode: 0666

- name: Create kafka instance
  command: "oc create -f {{ config_location }}/amq-kafka-instance.yaml"

- name: Waiting for  kafka instances to be deployed
  shell: |
    set -o pipefail && oc get pods | grep Running | grep {{ kafka_cluster_name }} |  wc -l
  register: install_status
  until: "'7' in install_status.stdout"
  retries: 60
  delay: 15
  args:
    executable: /bin/bash

- name: Copying over kafka topics
  template:
    src: templates/amq-kafka-topics.yaml.j2
    dest:  "{{ config_location }}/amq-kafka-topics.yaml"
    owner: "{{ default_owner }}"
    group: "{{ default_group }}"
    mode: 0666

- name: Create kafka topics
  command: "oc create -f {{ config_location }}/amq-kafka-topics.yaml"


