- name: Copying over quarkus-cafe-barista application
  template:
    src: templates/s2i/quarkus-cafe-barista.yaml.j2
    dest:  "{{ config_location }}/quarkus-cafe-barista.yaml"
    owner: "{{ default_owner }}"
    group: "{{ default_group }}"
    mode: 0666
  when: deployment_method == "s2i"

- name: Copying over quarkus-cafe-barista application
  template:
    src: templates/docker/quarkus-cafe-barista.yaml.j2
    dest:  "{{ config_location }}/quarkus-cafe-barista.yaml"
    owner: "{{ default_owner }}"
    group: "{{ default_group }}"
    mode: 0666
  when: deployment_method == "docker"

- name: Create quarkus-cafe-barista instance
  command: "oc create -f {{ config_location }}/quarkus-cafe-barista.yaml"

- name: Waiting for quarkus-cafe-barista build to complete
  shell: |
     set -o pipefail && oc get pods  | grep Completed | grep quarkus-cafe-barista | wc -l
  register: install_status
  when: deployment_method == "s2i"
  until: "'2' in install_status.stdout"
  retries: 120
  delay: 15
  args:
    executable: /bin/bash

- name: Waiting for quarkus-cafe-barista deployment
  shell: |
     set -o pipefail && oc get pods  | grep Running | grep quarkus-cafe-barista | wc -l
  register: install_status
  until: "'1' in install_status.stdout"
  retries: 60
  delay: 15
  args:
    executable: /bin/bash
