---
# Remove quarkus-cafe-customermock
# ------------------------------------------
- name: Delete quarkus-cafe-customermock instance
  k8s:
    state: absent
    src: "{{ config_location }}/quarkus-cafe-customermock.yaml"
  ignore_errors: yes

# Remove quarkus-cafe-web instance
# ------------------------------------------
- name: Delete quarkus-cafe-web instance
  k8s:
    state: absent
    src: "{{ config_location }}/quarkus-cafe-web.yaml"
  ignore_errors: yes

# Remove quarkus-cafe-kitchen 
# ------------------------------------------
- name: Delete quarkus-cafe-kitchen instance
  k8s:
    state: absent
    src: "{{ config_location }}/quarkus-cafe-kitchen.yaml"
  ignore_errors: yes

# Remove mongodb
# ------------------------------------------
- name: Delete mongodb instance
  command: "oc delete all --selector app=mongodb"
  ignore_errors: yes

# Remove mongodb secert
# ------------------------------------------
- name: Delete mongodb secret
  command: "oc delete secret mongodb"
  ignore_errors: yes

# Remove quarkus-cafe-core workload
# ------------------------------------------
- name: Delete quarkus-cafe-core instance
  k8s:
    state: absent
    src: "{{ config_location }}/quarkus-cafe-core.yaml"
  ignore_errors: yes

# Remove quarkus-cafe-barista workload
# ------------------------------------------
- name: Delete quarkus-cafe-barista instance
  k8s:
    state: absent
    src: "{{ config_location }}/quarkus-cafe-barista.yaml"
  ignore_errors: yes

# Remove AMQ workload
# ------------------------------------------
- name: Remove kafka topics
  k8s:
    state: absent
    src: "{{ config_location }}/amq-kafka-topics.yaml"
  ignore_errors: yes

- name: Remove kafka instance
  k8s:
    state: absent
    src: "{{ config_location }}/amq-kafka-instance.yaml"
  ignore_errors: yes

#- name: Waiting for  kafka instances to be deleted
#  shell: |
#    set -o pipefail && oc get pods | grep Running | grep {{ kafka_cluster_name }} | wc -l
#  register: install_status
#  until: "'No resources found' in install_status.stderr or '0' in install_status.stdout"
#  retries: 60
#  delay: 15
#  ignore_errors: yes
#  args:
#    executable: /bin/bash

- name: Remove AMQ Subscription
  k8s:
    state: absent
    src: "{{ config_location }}/amq-sub.yaml"
  ignore_errors: yes

# Remove Quarkus cafe project
# ------------------------------------------
- name: Delete Quarkus Cafe app project
  k8s:
    state: absent
    kind: Project
    api_version: project.openshift.io/v1
    definition:
      metadata:
        name: "{{ project_namespace }}"
        annotations:
          openshift.io/description: ""
          openshift.io/display-name: "{{ project_namespace }}"


# Leave this as the last task in the playbook.
# --------------------------------------------
- name: remove_workload tasks complete
  debug:
    msg: "Post-Software checks completed successfully - Removed"
  when: not silent|bool
