---
- name: Setting up workload for user
  debug:
    msg: "Setting up workload for user ocp_username = {{ ocp_username }}"

# Set up the combined dictionary for the workload
# 
# To Do: Adjust the names of your dictionaries here
- name: Set up ocp4_workload_example combined dictionary
  set_fact:
    ocp_workload_example: >-
      {{ ocp_workload_example_defaults
       | combine(ocp_workload_example_vars    | default( {} ),
                 ocp_workload_example_secrets | default( {} ), recursive=true )
      }}

# Because now secrets are part of the combined dictionary use
# verbosity 2 to prevent printing the dictionary during every run.
- name: Print combined role variables
  debug:
    var: ocp4_workload_example
    verbosity: 2

# To Do: Implement your Workload deployment tasks here
# If you have parameters for your workload use the "<role name> dictionary"
# -------------------------------------------------------------------------

- name: Example Workload, print dictionary values
  debug:
    msg: "{{ item }}"
  loop:
  - "Variable 1:      {{ ocp_workload_example.variable_1 }}"
  - "Variable 2:      {{ ocp_workload_example.variable_2 }}"
  - "Variable Secret: {{ ocp_workload_example.variable_secret }}"

- name: Create new project for quarkus-cafe
  command: "oc new-project {{ project_namespace }}"
  ignore_errors: yes

- name: Switch to project for quarkus-cafe
  command:  "oc project {{ project_namespace }}"

- name: AMQ Streams installation
  include_tasks: amq-streams-install.yml

- name: Configure quarkus-cafe-barista Application
  include_tasks: quarkus-cafe-barista.yml

- name: Configure quarkus-cafe-core Application
  include_tasks: quarkus-cafe-core.yaml

- name: Configure quarkus-cafe-kitchen Application
  include_tasks: quarkus-cafe-kitchen.yaml

- name: Configure quarkus-cafe-web Application
  include_tasks: quarkus-cafe-web.yaml

- name: Configure quarkus-cafe-customermock Application
  include_tasks: quarkus-cafe-customermock.yaml

# Leave this as the last task in the playbook.
# --------------------------------------------
- name: workload tasks complete
  debug:
    msg: "Workload Tasks completed successfully."
  when: not silent|bool
