---
## Deploy Gogs Git Server
- name: deploy gogs from template (persistent)
  shell: |
    {{ openshift_cli }} new-app -f https://raw.githubusercontent.com/tosin2013/gogs-openshift-docker/master/openshift/gogs-persistent-template.yaml \
        --param=HOSTNAME=gogs-gogs.{{ocp_apps_domain}} \
        --param=GOGS_VERSION={{ gogs_image_version }} \
        --param=SKIP_TLS_VERIFY={{ skip_tls_verify }} \
        --param=APPLICATION_NAME={{ gogs_service_name }} \
        -n {{ gogs_project_name }}
  when: not ephemeral|bool

- name: deploy gogs from template (ephemeral)
  shell: |
    {{ openshift_cli }} new-app -f https://raw.githubusercontent.com/tosin2013/gogs-openshift-docker/master/openshift/gogs-template.yaml \
        --param=HOSTNAME=gogs-gogs.{{ocp_apps_domain}} \
        --param=GOGS_VERSION={{ gogs_image_version }} \
        --param=SKIP_TLS_VERIFY={{ skip_tls_verify }} \
        --param=APPLICATION_NAME={{ gogs_service_name }} \
        -n {{ gogs_project_name }}
  when: ephemeral|bool

- name: set cpu and mem 
  shell: "{{ openshift_cli }} set resources dc/{{ gogs_service_name }} --limits=cpu={{ max_cpu }},memory={{ max_mem }} --requests=cpu={{ min_cpu }},memory={{ min_mem }} -n {{ gogs_project_name }}"

- name: wait for gogs application to start 
  uri:
    url: http://gogs-gogs.{{ocp_apps_domain}}
    status_code: 200
  register: result
  until: result.status == 200
  retries: "{{ gogs_deploy_retry_count }}"
  delay: "{{ gogs_deploy_retry_delay }}"