---
- name: remove_workload Tasks Started
  debug:
    msg: "Deletion of workload Tasks - Started"

#####
#
# Remove shared project
- name: Delete shared project
  command: "oc delete project {{ admin_project }}"
  ignore_errors: true
  tags: always

# Remove users projects
- name: Delete user projects
  command: "oc delete project {{ item }}"
  ignore_errors: true
  with_sequence: start={{user_count_start}} end={{ user_count_end }} format={{ user_format }}
  tags: always

# Remove users stage projects
- name: Delete user projects
  command: "oc delete project {{ item }}-stage"
  ignore_errors: true
  with_sequence: start={{user_count_start}} end={{ user_count_end }} format={{ user_format }}
  tags: always

 # Remove users projects
- name: Delete user prod projects
  command: "oc delete project {{ item }}-prod"
  ignore_errors: true
  with_sequence: start={{user_count_start}} end={{ user_count_end }} format={{ user_format }}
  tags: always

# Remove OpenShift Container Storage
- name: Delete OpenShift Container Storage
  command: "{{ openshift_cli }} delete -f {{ item }}"
  args:
    chdir: "{{ tmp_dir }}"
  with_items:
    - openshift-storage-operator.yml

# Remove che main project
- name: Delete che main project
  command: "oc delete project {{ che_project }}"
  ignore_errors: true
  tags: always

# Remove quay-operator project
- name: Create openshift quay objects
  command: "{{ openshift_cli }} delete -f {{ item }} -n quay-enterprise"
  args:
    chdir: "{{ tmp_dir }}/quay-operator"
  with_items:
    - ./config/samples/managed.quayregistry.yaml
    - ./deploy/quay-operator.subscription.yaml
    - ./deploy/quay-operator.operatorgroup.yaml 
  ignore_errors: true

- name: Create openshift quay objects
  command: "{{ openshift_cli }} delete -f ./deploy/quay-operator.catalogsource.yaml -n openshift-marketplace"
  args:
    chdir: "{{ tmp_dir }}/quay-operator"
  ignore_errors: true

# Remove noobaa
- name: remove openshift noobaa
  command: "create -n openshift-storage -f {{ item }}"
  args:
    chdir: "{{ tmp_dir }}/quay-operator"
  with_items:
    - ./kustomize/components/objectstorage/quay-datastore.noobaa.yaml
  ignore_errors: true
  
# Remove quay-enterprise project
- name: Delete quay-enterprise project
  command: oc delete project quay-enterprise
  ignore_errors: true
  tags: always

# Remove users quota
- name: Delete user quota
  command: oc delete clusterquota/clusterquota-{{ item }}
  ignore_errors: true
  with_sequence: start={{user_count_start}} end={{ user_count_end }} format={{ user_format }}
  tags: always

# Remove custom builds
- name: Delete custom builds
  command: oc delete all -l {{ item }} -n openshift
  with_items:
    - "build=custom-jenkins"
    - "role=jenkins-slave"
  ignore_errors: true
  tags: always

#
#####

- name: remove_workload Tasks Complete
  debug:
    msg: "Deletion of workload Tasks - Completed"
