{
 "title": "Cloud View",
 "tags": [ "CloudView" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   {
    "name": "projects",
    "query": "label_values(ceilometer_cpu,project)"
   },
   {
    "name": "top",
    "query": "1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "glance_api",
     "bucketAggs": [
      { "field": "startsAt", "id": "2", "settings": { "interval": "2m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "annotations.output.healthy",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "annotations.output.service:glance_api",
     "timeField": "startsAt"
    },
    {
     "alias": "nova_api",
     "bucketAggs": [
      { "field": "startsAt", "id": "2", "settings": { "interval": "2m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "annotations.output.healthy",
       "id": "1",
       "meta": {},
       "pipelineVariables": [
        { "name": "", "pipelineAgg": "select metric" }
       ],
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "annotations.output.service:nova_api",
     "timeField": "startsAt"
    },
    {
     "alias": "heat_api",
     "bucketAggs": [
      { "field": "startsAt", "id": "2", "settings": { "interval": "2m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "annotations.output.healthy",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "annotations.output.service:heat_api",
     "timeField": "startsAt"
    },
    {
     "alias": "neutron_api",
     "bucketAggs": [
      { "field": "startsAt", "id": "2", "settings": { "interval": "2m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "annotations.output.healthy",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "annotations.output.service:neutron_api",
     "timeField": "startsAt"
    },
    {
     "alias": "placement_api",
     "bucketAggs": [
      { "field": "startsAt", "id": "2", "settings": { "interval": "2m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "annotations.output.healthy",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "annotations.output.service:placement_api",
     "timeField": "startsAt"
    }
   ]
  },
  {
   "title": "Top $top Memory Consumers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "topk($top, sum by (plugin_instance, host) (collectd_libpodstats_pod_memory))",
     "legendFormat": "{{plugin_instance}} on {{host}}"
    }
   ]
  },
  {
   "title": "Top $top CPU Consumers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk($top, avg_over_time(collectd_libpodstats_pod_cpu_percent[10m]))",
     "legendFormat": "{{plugin_instance}} on {{host}}"
    }
   ]
  },
  {
   "title": "Uptime placement_api",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 8 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "startsAt", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "annotations.output.healthy",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "annotations.output.service:placement_api",
     "timeField": "startsAt"
    }
   ]
  },
  {
   "title": "Uptime neutron_api",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 8 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "startsAt", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "annotations.output.healthy",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "annotations.output.service:neutron_api",
     "timeField": "startsAt"
    }
   ]
  },
  {
   "title": "Uptime heat_api",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 8 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "startsAt", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "annotations.output.healthy",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "annotations.output.service:heat_api",
     "timeField": "startsAt"
    }
   ]
  },
  {
   "title": "Uptime nova_api",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 8 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "startsAt", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "annotations.output.healthy",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "annotations.output.service:nova_api",
     "timeField": "startsAt"
    }
   ]
  },
  {
   "title": "Uptime glance_api",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 8 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "startsAt", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "annotations.output.healthy",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "annotations.output.service:glance_api",
     "timeField": "startsAt"
    }
   ]
  },
  { "title": "Instances", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Project $projects",
   "type": "grafana-polystat-panel",
   "description": "Click instance for drill down view",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 13 },
   "repeat": "projects",
   "targets": [
    {
     "expr": "ceilometer_cpu{project=\"$projects\"}",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "Project $projects",
   "type": "grafana-polystat-panel",
   "description": "Click instance for drill down view",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "ceilometer_cpu{project=\"$projects\"}",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  { "title": "Service Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Horizon CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "collectd_libpodstats_pod_cpu_percent{plugin_instance=\"horizon\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Horizon Memory Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "collectd_libpodstats_pod_memory{plugin_instance=\"horizon\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Ceph CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (host) (collectd_libpodstats_pod_cpu_percent{plugin_instance=~\"ceph-.*\"})",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Ceph Memory Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (host) (collectd_libpodstats_pod_memory{plugin_instance=~\"ceph-.*\"})",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Nova CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (host) (collectd_libpodstats_pod_cpu_percent{plugin_instance=~\"nova.*\"})",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Nova Memory Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (host) (collectd_libpodstats_pod_memory{plugin_instance=~\"nova.*\"})",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Ceilometer CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (host) (collectd_libpodstats_pod_cpu_percent{plugin_instance=~\"ceilometer.*\"})",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Ceilometer Memory Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (host) (collectd_libpodstats_pod_memory{plugin_instance=~\"ceilometer.*\"})",
     "legendFormat": "{{host}}"
    }
   ]
  },
  { "title": "Cloud Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Networking",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "metrics": [
      {
       "field": "payload.traits.size",
       "id": "1",
       "meta": {},
       "settings": { "size": 500 },
       "type": "raw_document"
      }
     ],
     "query": "_index: ceilometer_network_*",
     "timeField": "payload.generated"
    },
    {
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 500 },
       "type": "raw_document"
      }
     ],
     "query": "_index: ceilometer_subnet_*",
     "timeField": "payload.generated"
    },
    {
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 500 },
       "type": "raw_document"
      }
     ],
     "query": "_index: ceilometer_port_*",
     "timeField": "payload.generated"
    }
   ]
  },
  {
   "title": "Volumes",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {
     "metrics": [
      {
       "field": "payload.traits.size",
       "id": "1",
       "meta": {},
       "settings": { "size": 500 },
       "type": "raw_document"
      }
     ],
     "query": "_index: ceilometer_volume_*",
     "timeField": "payload.generated"
    }
   ]
  },
  {
   "title": "Compute",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {
     "metrics": [
      {
       "field": "payload.traits.size",
       "id": "1",
       "meta": {},
       "settings": { "size": 500 },
       "type": "raw_document"
      }
     ],
     "query": "_index: ceilometer_compute_*",
     "timeField": "payload.generated"
    }
   ]
  },
  {
   "title": "Identity",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {
     "metrics": [
      {
       "field": "payload.traits.size",
       "id": "1",
       "meta": {},
       "settings": { "size": 500 },
       "type": "raw_document"
      }
     ],
     "query": "_index: ceilometer_identity_*",
     "timeField": "payload.generated"
    }
   ]
  },
  {
   "title": "Images",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 61 },
   "targets": [
    {
     "metrics": [
      {
       "field": "payload.traits.size",
       "id": "1",
       "meta": {},
       "settings": { "size": 500 },
       "type": "raw_document"
      }
     ],
     "query": "_index: ceilometer_image*",
     "timeField": "payload.generated"
    }
   ]
  }
 ]
}