---
- name: Create argocd 
  k8s:
    state: present
    definition: "{{ lookup('template', './templates/argocd_cr.yaml.j2' ) | from_yaml }}"

- name: Wait for argocd to be available
  k8s_info:
    api_version: argoproj.io/v1alpha1
    kind: ArgoCD
    name: argocd
    namespace: labs-argocd
  register: result
  until: result | json_query("resources[0].status.phase=='Available'")
  retries: 400
  delay: 2
