---
- name: Create kie secrets for users
  k8s:
    definition:
      kind: Secret
      apiVersion: v1
      metadata:
        name: kie-admin
        namespace: "{{ns}}"
      data:
        password: "{{workshop_kie_user_password | b64encode }}"
        user: "{{workshop_kie_user_name | b64encode}}"
      type: Opaque
  vars:
    user: "{{ item[0] }}"
    ns: "{{ item[0] }}-{{ item[1] }}"    
  loop: "{{ users|product(['prod'])|list }}"

