---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: codeready-workspaces
  namespace: labs-infra
spec:
  channel: latest
  installPlanApproval: Automatic
  name: codeready-workspaces
  source: olm-snapshot-redhat-catalog
  sourceNamespace: openshift-marketplace
