apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:  
  name: prometheus-operator
  namespace: labs-prometheus
spec:
  channel: beta
  installPlanApproval: Automatic
  name: prometheus
  source: olm-snapshot-community-catalog
  sourceNamespace: openshift-marketplace